version: "3.8"
services:
  postgres-db:
    container_name: recipeweb
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: web
      POSTGRES_DB: recipeweb
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5438:5432"

volumes:
  postgresql_data:
    driver: local